### ISSUE TITLE
0.0.1 Todos

### ISSUE THREAD

**Issue by sorrycc** [umijs/tnf#1]
> wip & pr welcome.

- [x] 工程化：添加 github ci，每个 pr 里跑 npm run ci，1h
- [x] 工程化：添加 e2e 测试方法，并纳入 ci，基于 playwright 做 browser 测试，2h
- [x] 工程化：使用 changesets 做发布和 changelog 生成，1h @xiaohuoni 
- [x] 添加 hackernews example，参考 https://github.com/dvajs/dva-hackernews ，3h @Wu-kung
- [ ] 添加 ant-design-pro example，8h @xiaohuoni 
- [ ] 添加 todos example，1h
- [x] 添加 dev command，1）build + watch:true，2）需要支持 fallback 路由，让访问非跟路由时也正常而不是 404，2h
- [ ] 实现类 umi 的配置式路由，添加 src/router.ts，实现一个函数，输入是路由配置，输出是 generate 后的编程式路由代码，调用或参考 @tanstack/router-generator，4h-8h
- [ ] 支持 ssr，1）生成 server entry，2）新增一次构建，以 ssr entry 为入口，2h
- [x] 补充 e2e 测试用例，1h

**Comment by moonlitusun** [comment]
dev command 这个 如果用mako起dev的话支持fallback配置吗 看了下mako文档 devServer的配置很少 也没有可以拦截的地方

**Comment by xiaohuoni** [comment]
@moonlitusun https://github.com/umijs/mako/blob/master/packages/bundler-mako/index.js#L84

**Comment by xiaohuoni** [comment]
## ant-design-pro

要完成全套功能有一些必要功能，感兴趣的朋友可以看看，功能上应该是对标 umi max 的，但是所有的功能实现都尽可能的白盒，

- [ ] [布局与菜单](https://umijs.org/docs/max/layout-menu)
- [x] [antd](https://umijs.org/docs/max/antd) https://github.com/umijs/tnf/pull/15
- [ ] [图表](https://umijs.org/docs/max/charts)
- [ ] [数据流](https://umijs.org/docs/max/data-flow)
- [ ] [请求](https://umijs.org/docs/max/request) @xiaohuoni 
       1、用 tanstack router 的 loader 定义路由级的 load 请求
2、请求用 fetch，看下是否够用
3、请求方案如有需要，用 tanstack query
- [ ] [权限](https://umijs.org/docs/max/access)
- [ ] [国际化](https://umijs.org/docs/max/i18n)
- [ ] [dva](https://umijs.org/docs/max/dva)

**Comment by sorrycc** [comment]
Follow up at https://github.com/umijs/tnf/issues/2 .
