### ISSUE TITLE
antd 不支持 react@19

### ISSUE THREAD

**Issue by xiaohuoni** [umijs/tnf#21]
有依赖包锁了 react@19
项目里面指定安装 react@18 不能解答这个问题，需要 
```json
  "resolutions": {
    "react": "18.3.1",
    "react-dom": "18.3.1"
  },
```
https://github.com/umijs/tnf-ant-design-pro/blob/main/package.json#L79

**Comment by sorrycc** [comment]
Fixed in https://github.com/umijs/tnf/pull/19 .

**Comment by xiaohuoni** [comment]
https://github.com/ant-design/ant-design/issues/51339
