### ISSUE TITLE
提取 create-tnf package 到根目录

### ISSUE THREAD

**Issue by sorrycc** [umijs/tnf#24]
## Background

create 命令随着 tnf 主包走会让 npm create tnf 变慢，这没有必要。

## Solution

1、根目录创建 create-tnf 目录，这是一个 npm 包，name 为 create-tnf
2、pnpm-workspace.yaml 里需要包含这个目录
3、迁移 src/create.ts 到 create-tnf 
4、create-tnf 里估计需要配套的 tsconfig.json 和 .fatherrc.ts

**Comment by QDyanbing** [comment]
我先尝试下
