### ISSUE TITLE
约定式的 src/global.{less,css}

### ISSUE THREAD

**Issue by sorrycc** [umijs/tnf#26]
### Problem

沿袭之前 Umi 的约定，目前 src/global.{less,css} 没有生效。但实际 example 里又发现这类需求无法避免。

### Solution

修改 src/sync.ts，当存在 src/global.{less,css} 时，在临时生成的 client.tsx 里增加对此文件的 import 。

### Importance

would make my life easier

**Comment by iamwangqing** [comment]
认领

**Comment by xiaohuoni** [comment]
@iamwangqing 
可以顺便和 overrides 一起做了，
global 最前，权重最低。
overrides.(css|less) 最后，权重最高。

**Comment by sorrycc** [comment]
Closed via #28

**Comment by sorrycc** [comment]
overrides 有点麻烦的，基于之前 umi 的实现的话，得自动加一些 wrapper 来增加权重。但如果增加 wrapper，在 global.less 里手动增加也能解决这个问题。这是我纠结的点。
