### ISSUE TITLE
RFC: tnf g tailwindcss

### ISSUE THREAD

**Issue by xiaohuoni** [umijs/tnf#31]
### Problem

有些功能或者内置功能应该都支持组装式的用法，允许用户使用当前项目中的某个文件来覆盖约定或者默认生成的文件。
比如程序主入口文件 `src/.tnf/client.tsx` 应该允许用户使用 `src/client.tsx` 文件覆盖它。
开启 tailwindcss 功能，需要搭配使用 `src/tailwind.css` 和 `tailwind.config.js`。
这些文件的初始版本都太模版化了，完全可以通过脚本提供。

### Solution

需要开始某个功能或者暴露某个功能时，执行 tnf setup 或者 tnf init

```bash
$ tnf setup
# 未提供参数则提供列表
   请选择需要初始化的功能?
❯ entry
  tailwindcss
  other

$ tnf setup tailwindcss
# 提供参数则直接执行
```

### Importance

would make my life easier

**Comment by sorrycc** [comment]
这个功能可以做到 generate 里。

```bash
$ tnf g
$ tnf g tailwindcss
```

**Comment by iamwangqing** [comment]
大概实现思路，大佬们看看可以吗
1、用户未提供命令：`tnf g`则使用`@clack/prompts`中的`select`让用户选择一个命令`entry`or`tailwindcss`
2、`entry`命令复制`.tnf`下的`client.tsx`到`src/clinent.tsx`中，增加`.tnfrc.ts`中的配置项(增加一个配置？)
3、`tailwindcss`命令则自动生成`src/tailwind.css `和 `tailwind.config.js`到对应位置

**Comment by sorrycc** [comment]
> 3、tailwindcss命令则自动生成src/tailwind.css 和 tailwind.config.js到对应位置

先做 3 吧。 @iamwangqing 另两个需要更系统的设计。

**Comment by iamwangqing** [comment]
> > 3、tailwindcss命令则自动生成src/tailwind.css 和 tailwind.config.js到对应位置
> 
> 先做 3 吧。 @iamwangqing 另两个需要更系统的设计。

好的，那我先把3做掉
