### ISSUE TITLE
tailwindcss 功能，不强制提供配置文件

### ISSUE THREAD

**Issue by xiaohuoni** [umijs/tnf#32]
### Problem

现在开启 tailwindcss 功能，需要用户强制提供 `src/tailwind.css` 和 `tailwind.config.js`

### Solution

1、 如果有 `src/tailwind.css` 和 `tailwind.config.js`，保留现有逻辑
2、没有 `src/tailwind.css`
generateTailwindcss：
   修改入口文件为 `input: path.join(rootPath, 'tailwindDirectives.css'),`
   生成 tailwindDirectives 文件

3、如果没有 `tailwind.config.js` 
generateFile：给 tailwindcss 传递 content （需要看一下能不能传），不能传的话，tmp 目录中生成简单的 `tailwind.config.js` 

用户需要配置 tailwind 的话，还是需要显示的 `tailwind.config.js` 文件

### Importance

nice to have

**Comment by Xy2002** [comment]
有个问题，在我提交pr的时候，我特意将Tailwind生成的css放到了一个单独的文件夹，因为在每次hmr的时候，`.tnf`这个文件夹都会被删除然后重建，会导致入口文件虽然import了Tailwind的产物，但是实际上没有正常导入，我试验了几个小时后发现是因为Tailwind的产物不能每次热更新的时候都删除重建。

在dev模式下，当你做出一些有关Tailwind类的修改后，你可以发现，`src/.tnf/tailwind/tailwind.css`虽然是正确的，但是打开Chrome DevTools查看`client.css`后，可以看到Tailwind的产物还是旧的，并没有随着新的`tailwind.css`进行更新。

我有想过修改`sync.ts`里的逻辑，在每次sync的时候删除`.tnf`文件里除了Tailwind产物以外的文件，但是我怕有性能问题就没改，所以最后决定将Tailwind产物放到一个新的文件夹里。

请问有什么好的解决办法吗😂

**Comment by xiaohuoni** [comment]
@Xy2002 没有注意到，要不要给个复现，看看是不是 mako 的缓存问题？

**Comment by Xy2002** [comment]
> @Xy2002 没有注意到，要不要给个复现，看看是不是 mako 的缓存问题？

给一个[CodeSandbox](https://codesandbox.io/p/github/Xy2002/tnf/master?import=true)，运行`pnpm run dev`后，修改`examples/tailwindcss/pages/index.tsx`的随意一个标签的className，修改两次以上就可以复现这个问题了

**Comment by Xy2002** [comment]
@xiaohuoni 我也不知道是不是mako的缓存问题，我到现在都没搞懂为什么HMR模式下Tailwind的产物不能被删除重建，甚至还会报错导致程序崩溃（不太确定是不是这个原因），我只能通过实验得出这个结论，如果找到原因了，还请麻烦大佬讲解一下🤣
