### ISSUE TITLE
.gitignore 规则错误

### ISSUE THREAD

**Issue by Xy2002** [umijs/tnf#36]
### Describe the bug

这行 `/examples/*/.tnf` 规则应该是错的，因为 `.tnf` 文件夹是位于 `src` 文件夹下的，这行规则无法正确匹配 `.tnf` 目录

### Reproduction

在任意一个examples运行dev即可复现

### Severity

annoyance

**Comment by sorrycc** [comment]
It's changed by https://github.com/umijs/tnf/commit/1d6eb5c673513987a574dcb7bede126176baf3f9 .
