### ISSUE TITLE
support clickToComponent

### ISSUE THREAD

**Issue by sorrycc** [umijs/tnf#50]
### Problem

We need to support clickToComponent.

### Solution

1、基于 https://github.com/ericclemmons/click-to-component ，内置在 tnf 依赖里，但要锁死版本（有前科..）
2、修改 sync_client_entry.ts，参考 TanStackRouterDevtools 的加法，只在 dev 有效
3、修改 config.ts，补上相应的 alias
4、Umi 里有类似实现，可供参考
5、bundler 为 mako 时，注意路径问题，参考 https://github.com/umijs/umi/pull/12775

### Alternatives

https://github.com/aaamoon/react1s

### Importance

nice to have

**Comment by QDyanbing** [comment]
这个还没人吗，要不我尝试下;不知道是不是这样弄
