### ISSUE TITLE
需要 defineConfig 以实现在 .tnfrc.ts 获得类型提示支持

### ISSUE THREAD

**Issue by Xy2002** [umijs/tnf#55]
### Problem

目前在 `.tnfrc.ts` 中，配置 tnf 还没有类型提示，得看文档和源码才知道如何配置。

### Solution

希望能实现一个类似于 rollup 和其他框架一样的 `defineConfig` 函数。

但是目前 tnf 还没有一个 index 文件，在 `package.json` 只 exports 了 `router` 和 `package.json`，因此需要进行初步规划才知道该如何设计。

### Importance

nice to have

**Comment by sorrycc** [comment]
done via https://github.com/umijs/tnf/commit/9072730adeed491805e17376bdbd1aa78ab30c19
