### ISSUE TITLE
Bug: ssr hydrate unmatch problem

### ISSUE THREAD

**Issue by sorrycc** [umijs/tnf#58]
### Describe the bug

<img width="722" alt="image" src="https://github.com/user-attachments/assets/3785391b-1115-4c77-ac57-994c4631064f">

### Reproduction

```bash
$ cd examples/ssr
$ pnpm build
$ node ./server
```

### Severity

blocking all usage of TNF

**Comment by QDyanbing** [comment]
<img width="1620" alt="image" src="https://github.com/user-attachments/assets/1a3c9510-f858-4626-8588-4494746e64c4">

**Comment by Jinbao1001** [comment]
closed with #59
