### ISSUE TITLE
refactor(ssr): extract StartClient, StartServer and Meta from @tanstack/start

### ISSUE THREAD

**Issue by sorrycc** [umijs/tnf#63]
### Problem

目前 ssr 的实现需要项目依赖 @tanstack/start ，这是开发过程中的临时解，需要提取到 tnf 里。

### Solution

Implement StartClient, StartServer and Meta in tnf.

### Importance

i cannot use TNF without it

**Comment by QDyanbing** [comment]
我来

**Comment by sorrycc** [comment]
Closed via #64
